<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Broiler.Writer</RootNamespace>
    <AssemblyName>Broiler.Writer.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Broiler.Writer.FormatCodes\Broiler.Writer.FormatCodes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Broiler.Writer.Windows" />
    <InternalsVisibleTo Include="Broiler.Writer.Linux" />
    <InternalsVisibleTo Include="Broiler.Writer.Android" />
    <InternalsVisibleTo Include="Broiler.Writer.FormatCodes.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Broiler.Graphics" Version="0.1.0-preview.5" />
    <PackageReference Include="Broiler.Documents.Docx" Version="0.1.0-preview.21" />
    <PackageReference Include="Broiler.Documents.Html" Version="0.1.0-preview.21" />
    <PackageReference Include="Broiler.Documents.Markdown" Version="0.1.0-preview.21" />
    <PackageReference Include="Broiler.Documents.Odt" Version="0.1.0-preview.21" />
    <PackageReference Include="Broiler.Documents.Rtf" Version="0.1.0-preview.21" />
    <PackageReference Include="Broiler.UI.AboutDialog" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.AboutDialog.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Button.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.ComboBox.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Dialog.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.FileDialog.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.FontDialog.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.FormatCodeView" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.FormatCodeView.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Label.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Menu.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.RichEdit" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.RichEdit.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Splitter.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Toolbar.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Tooltip.Standard" Version="0.1.0-preview.9" />
    <PackageReference Include="Broiler.UI.Window.Standard" Version="0.1.0-preview.9" />
  </ItemGroup>

</Project>
