<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Broiler.Writer</RootNamespace>
    <AssemblyName>Broiler.Writer.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Broiler.Writer.FormatCodes\Broiler.Writer.FormatCodes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Broiler.Writer.Windows" />
    <InternalsVisibleTo Include="Broiler.Writer.Linux" />
    <InternalsVisibleTo Include="Broiler.Writer.Android" />
    <InternalsVisibleTo Include="Broiler.Writer.FormatCodes.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Broiler.Graphics" />
    <PackageReference Include="Broiler.Documents.Docx" />
    <PackageReference Include="Broiler.Documents.Html" />
    <PackageReference Include="Broiler.Documents.Markdown" />
    <PackageReference Include="Broiler.Documents.Odt" />
    <PackageReference Include="Broiler.Documents.Rtf" />
    <PackageReference Include="Broiler.UI.AboutDialog" />
    <PackageReference Include="Broiler.UI.AboutDialog.Standard" />
    <PackageReference Include="Broiler.UI.Button.Standard" />
    <PackageReference Include="Broiler.UI.ComboBox.Standard" />
    <PackageReference Include="Broiler.UI.Dialog.Standard" />
    <PackageReference Include="Broiler.UI.Edit.Standard" />
    <PackageReference Include="Broiler.UI.FileDialog.Standard" />
    <PackageReference Include="Broiler.UI.FontDialog.Standard" />
    <PackageReference Include="Broiler.UI.FormatCodeView" />
    <PackageReference Include="Broiler.UI.FormatCodeView.Standard" />
    <PackageReference Include="Broiler.UI.Label.Standard" />
    <PackageReference Include="Broiler.UI.Menu.Standard" />
    <PackageReference Include="Broiler.UI.RichEdit" />
    <PackageReference Include="Broiler.UI.RichEdit.Standard" />
    <PackageReference Include="Broiler.UI.Splitter.Standard" />
    <PackageReference Include="Broiler.UI.Toolbar.Standard" />
    <PackageReference Include="Broiler.UI.Tooltip.Standard" />
    <PackageReference Include="Broiler.UI.Window.Standard" />
  </ItemGroup>

</Project>
