<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Broiler.Writer</RootNamespace>
    <AssemblyName>Broiler.Writer.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Broiler.Writer.FormatCodes\Broiler.Writer.FormatCodes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Broiler.Writer.Windows" />
    <InternalsVisibleTo Include="Broiler.Writer.Linux" />
    <InternalsVisibleTo Include="Broiler.Writer.Android" />
    <InternalsVisibleTo Include="Broiler.Writer.FormatCodes.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Broiler.Graphics" Version="0.1.0-preview.3" />
  </ItemGroup>

</Project>
